modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="editableplayernbthack"
version="${file.jarVersion}"
displayName="Editable Player NBT Hack"
displayURL="https://github.com/sashafiesta/editableplayernbthack"
displayTest="IGNORE_ALL_VERSION"
authors="sashafiesta"
description='''
Removes the probably artificial limitation in the vanilla game of disallowing the editing of player NBT data.
'''
[[dependencies.editableplayernbthack]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.editableplayernbthack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.19)"
    ordering="NONE"
    side="BOTH"
